data_dir: ../../data
model_save_dir: ../../models
model_save_name_prefix: GatedDeltaNet_rtx_2080_
model_type: GatedDeltaNet
continue_training: false
seed: 2025

wandb: true # whether to log to wandb for testing

lr_scheduler: cosine
initial_lr: 0.00001
learning_rate: 0.0000001
loss: mse # mae
scaler: min_max

batch_size: 64
num_epochs: 100
validation_interval: 5

context_len: 512
min_seq_len: 64
max_seq_len: 512

encoding_dropout: 0.0
sample_multi_pred: 0.5
sin_pos_enc: false
sin_pos_const: 100
sub_day: true
