data_dir: ./data
model_save_dir: ./models
model_save_name_prefix: GatedDeltaNet_rtx_2080
continue_training: false
seed: 2025
debugging: false
wandb: true # whether to log to wandb for testing

lr_scheduler: cosine
initial_lr: 0.00001
learning_rate: 0.0000001
loss: mse # mae
scaler: min_max

batch_size: 64
num_epochs: 100
num_training_iterations_per_epoch: 100
num_validation_iteration_per_epoch: 100
training_rounds: 100
validation_rounds: 100
num_val_samples_to_plot: 6

sample_multi_pred: 0.5
context_len: 512
min_seq_len: 128
max_seq_len: 512
pred_len_sample: true
pred_len_min: 32
pred_len: 64

BaseModelConfig:
  sin_pos_enc: false
  sin_pos_const: 100
  sub_day: true
  encoding_dropout: 0.0
  handle_constants_model: false

MultiStepModel:  
  residual: false
  num_encoder_layers: 2
  token_embed_dim: 1024
  use_gelu: true
  use_input_projection_norm: false
  use_global_residual: false
  linear_sequence_length: 15
  use_dilated_conv: true
  dilated_conv_kernel_size: 5
  dilated_conv_max_dilation: 3

EncoderConfig:
  encoder_type: GatedDeltaNet
  num_layers: 2
  num_heads: 4  
  norm: true
  norm_type: layernorm
  residual: false   
  enc_conv: true
  dilated_conv_kernel_size: 5  
  dilated_conv_max_dilation: 3
  block_expansion: 2.0