data_dir: ./data
model_path: ./models
model_name: SineWave_DeltaNet_
continue_training: false
seed: 2025
debugging: false
wandb: true # whether to log to wandb


lr_scheduler: cosine
initial_lr: 0.0001 # 1e-4
learning_rate: 0.0000001 # 1e-7
loss: mse # mae
scaler: custom_robust  
adaptive_loss_normalization: false 
gradient_clip_val: 100

gradient_accumulation_enabled: false
accumulation_steps: 2  # Number of batches to accumulate before updating (effective batch size = batch_size * accumulation_steps)

max_history_length: 1024
max_prediction_length: 900
batch_size: 256
num_epochs: 100
num_training_iterations_per_epoch: 10
log_interval: 1

BaseModelConfig:
  sin_pos_enc: false
  sin_pos_const: 100
  encoding_dropout: 0.0
  handle_constants_model: false

  time_feature_config:
    use_enhanced_features: true
    use_holiday_features: false
    use_index_features: true
    k_max: 6
    include_seasonality_info: true 

MultiStepModel:  
  residual: false
  num_encoder_layers: 2
  token_embed_dim: 256  
  
  use_input_projection_norm: false
  use_global_residual: false
  linear_sequence_length: 15
  

EncoderConfig:
  encoder_type: DeltaNet
  token_embed_dim: 256 # TODO: remove duplicate
  num_layers: 2
  num_heads: 4  
  norm: true
  norm_type: layernorm
  residual: true
  enc_conv: true
  dilated_conv_kernel_size: 5  
  dilated_conv_max_dilation: 3
  block_expansion: 2.0


range_proportions:
  short: 0.34
  medium: 0.33
  long: 0.33

generator_proportions:
  short:    
    forecast_pfn: 0.00
    gp: 0.50
    kernel: 0.00
    lmc: 0.
    sine_wave: 0.5
  medium:
    forecast_pfn: 0.00
    gp: 0.50
    kernel: 0.00
    lmc: 0.
    sine_wave: 0.5
  long:   
    forecast_pfn: 0.00
    gp: 0.50
    kernel: 0.00
    lmc: 0.
    sine_wave: 0.5
    