data_dir: ./data
model_path: ./models
model_name: Multivariate_DeltaNet_
continue_training: false
seed: 2025
debugging: false
wandb: true # whether to log to wandb


lr_scheduler: cosine
initial_lr: 0.00001 # 1e-5
learning_rate: 0.0000001 # 1e-7
loss: mse # mae
scaler: custom_robust

batch_size: 128
num_epochs: 50
num_training_iterations_per_epoch: 50
log_interval: 1

BaseModelConfig:
  sin_pos_enc: false
  sin_pos_const: 100
  encoding_dropout: 0.0
  handle_constants_model: false

  time_feature_config:
    use_enhanced_features: true
    use_holiday_features: false
    use_index_features: true
    auto_adjust_k_max: true
    include_seasonality_info: true 

MultiStepModel:  
  residual: false
  num_encoder_layers: 2
  token_embed_dim: 256  
  use_gelu: true
  use_input_projection_norm: false
  use_global_residual: false
  linear_sequence_length: 15
  use_dilated_conv: true
  dilated_conv_kernel_size: 5
  dilated_conv_max_dilation: 3
  cross_channel_attention_heads: 4

EncoderConfig:
  encoder_type: DeltaNet
  token_embed_dim: 256 # TODO: remove duplicate
  num_layers: 2
  num_heads: 4  
  norm: true
  norm_type: layernorm
  residual: false   
  enc_conv: true
  dilated_conv_kernel_size: 5  
  dilated_conv_max_dilation: 3
  block_expansion: 2.0


range_proportions:
  short: 0.34
  medium: 0.33
  long: 0.33

generator_proportions:
  short:    
    forecast_pfn: 0.05
    gp: 0.25
    kernel: 0.25
    lmc: 0.45
  medium:
    forecast_pfn: 0.05
    gp: 0.3
    kernel: 0.25
    lmc: 0.45
  long:   
    forecast_pfn: 0.05
    gp: 0.3
    kernel: 0.25
    lmc: 0.45

max_context_length: 1024