data_dir: ./data
model_path: ./models
model_name: Univariate_SineWave
continue_training: false
seed: 2025
debugging: false
wandb: true # whether to log to wandb


lr_scheduler: cosine
initial_lr: 0.0001 # 1e-4
learning_rate: 0.0000001 # 1e-7
scaler: custom_robust
adaptive_loss_normalization: false 
gradient_clip_val: 100

gradient_accumulation_enabled: false
accumulation_steps: 8  # Number of batches to accumulate before updating (effective batch size = batch_size * accumulation_steps)

max_history_length: 1024
max_prediction_length: 900
# batch_size: 128 # Not needed when using pregenerated data with batch size 128
num_epochs: 1000
num_training_iterations_per_epoch: 100
log_interval: 10

# TimeSeriesModel Configuration
TimeSeriesModel:
  # Core architecture
  embed_size: 128
  token_embed_dim: 256
  num_encoder_layers: 2
  
  # Scaling and preprocessing
  epsilon: 0.001
  scaler_clamp_value: null
  handle_constants: false
  
  # Time features
  time_feature_config:
    use_enhanced_features: true
    use_holiday_features: false
    use_index_features: true
    k_max: 6
    include_seasonality_info: true
  sin_pos_enc: false
  sin_pos_const: 100
  encoding_dropout: 0.0
  
  # Model architecture
  use_gelu: true
  use_input_projection_norm: false
  use_global_residual: false
  linear_sequence_length: 15
  use_dilated_conv: true
  dilated_conv_kernel_size: 5
  dilated_conv_max_dilation: 3
  
  # Encoder configuration
  encoder_config:
    token_embed_dim: 256
    num_heads: 4


range_proportions:
  short: 0.34
  medium: 0.33
  long: 0.33

generator_proportions:
  short:    
    forecast_pfn: 0.00
    gp: 0.50
    kernel: 0.00
    lmc: 0.
    sine_wave: 0.5
  medium:
    forecast_pfn: 0.00
    gp: 0.50
    kernel: 0.00
    lmc: 0.
    sine_wave: 0.5
  long:   
    forecast_pfn: 0.00
    gp: 0.50
    kernel: 0.00
    lmc: 0.
    sine_wave: 0.5
    