data_dir: ./data
model_path: ./models
model_name: Multivariate_GatedDeltaNet_
continue_training: false
seed: 2025
debugging: false
wandb: false # whether to log to wandb for testing


lr_scheduler: cosine
initial_lr: 0.00001
learning_rate: 0.0000001
loss: mse # mae
scaler: custom_robust

batch_size: 8
num_epochs: 50
num_training_iterations_per_epoch: 10

BaseModelConfig:
  sin_pos_enc: false
  sin_pos_const: 100
  sub_day: true
  encoding_dropout: 0.0
  handle_constants_model: false

MultiStepModel:  
  residual: false
  num_encoder_layers: 2
  token_embed_dim: 1024
  use_gelu: true
  use_input_projection_norm: false
  use_global_residual: false
  linear_sequence_length: 15
  use_dilated_conv: true
  dilated_conv_kernel_size: 5
  dilated_conv_max_dilation: 3

EncoderConfig:
  encoder_type: GatedDeltaNet
  token_embed_dim: 1024 # Todo: remove duplicate
  num_layers: 2
  num_heads: 4  
  norm: true
  norm_type: layernorm
  residual: false   
  enc_conv: true
  dilated_conv_kernel_size: 5  
  dilated_conv_max_dilation: 3
  block_expansion: 2.0


range_proportions:
  short: 0.34
  medium: 0.33
  long: 0.33

generator_proportions:
  short:    
    forecast_pfn: 0.3
    gp: 0.3
    kernel: 0.35
    lmc: 0.05
  medium:
    forecast_pfn: 0.2
    gp: 0.2
    kernel: 0.2
    lmc: 0.05
  long:   
    forecast_pfn: 0.1
    gp: 0.3
    kernel: 0.05
    lmc: 0.55